// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpW3yDtS6bFgVlcjwdFAjRPTQaFdc_Jt8',
    appId: '1:490388366376:web:4af5539e6b9c05da8ec11d',
    messagingSenderId: '490388366376',
    projectId: 'attendanceapphong',
    authDomain: 'attendanceapphong.firebaseapp.com',
    storageBucket: 'attendanceapphong.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgS9LT1J9naZdZagGVMHsvJ9aMK5X2HT4',
    appId: '1:490388366376:android:00fd6a64a3266ad28ec11d',
    messagingSenderId: '490388366376',
    projectId: 'attendanceapphong',
    storageBucket: 'attendanceapphong.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrd_ckrFCYEzPbmS-865h90IC1dYvvskI',
    appId: '1:490388366376:ios:5917274075a213168ec11d',
    messagingSenderId: '490388366376',
    projectId: 'attendanceapphong',
    storageBucket: 'attendanceapphong.appspot.com',
    iosClientId: '490388366376-kq2moo1qoj9cf6gd0rvfr1e4ohiocigr.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrd_ckrFCYEzPbmS-865h90IC1dYvvskI',
    appId: '1:490388366376:ios:c8b69d938ef27a188ec11d',
    messagingSenderId: '490388366376',
    projectId: 'attendanceapphong',
    storageBucket: 'attendanceapphong.appspot.com',
    iosClientId: '490388366376-dlhj1a27n60koi9p432h05jqt87tmlru.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp.RunnerTests',
  );
}
